rvm:
- 1.9.3
- 2.0.0
- 2.1.0
- 3.2.2

before_script:
  - "sudo apt-get install python-dev python-pip python-lxml libcairo2 libpango1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info"
  - "sudo pip install weasyprint"
